### ISSUE TITLE
Support for .NET Core 3.1

### ISSUE THREAD

**Issue by icnocop** [jnprr/blazor-breadcrumb-navigation#1]
Hi.

Thank you for Blazor Breadcrumb Navigation!

I'm wondering if there's a specific reason this component targets .NET Core 5?

For example, do you know of any issues that would prevent this component from targeting .NET Core 3.1?

Thank you.

**Comment by cschulzsuper** [comment]
Sorry, for the late reply. The breadcrumb navigation uses CSS isolation for the standard layout. CSS Isolation for blazor components was introduced in .NET 5.

I just had a look on what would happen, if I would change the target framework to .NET Core 3.1. The layout will break, but the logic still works.

Since the project was based on .NET 5 from the beginning, I would like to stay at .NET 5.
